spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

telegram:
  api:
    bot:
      enabled: ${TELEGRAM_BOT_ENABLED}
      name: ${TELEGRAM_BOT_NAME}
      token: ${TELEGRAM_BOT_TOKEN}